name: ci

on: [push]

jobs:
  integration-redisearch-1-6-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Deps
      run: |
        apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      run: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.6.1 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
