name: coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev -y
        gem install bundler --no-document
        bundle install
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.2.0
      env:
        CC_TEST_REPORTER_ID: fec34310f03fd2cc767a85fa23d5102f3dca67b9cc967a48d9940027731394e8
      with:
        coverageCommand: bundle exec rake test:unit
