name: unit_tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler --no-document
        BUNDLE_GEMFILE=Gemfile bundle install
    - name: Run tests
      run: BUNDLE_GEMFILE=Gemfile bundle exec rake test:unit
