name: unit_tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x', 'ruby-head' ]
        gemfile: [ 'Gemfile', 'gemfiles/activerecord_51.gemfile', 'gemfiles/activerecord_52.gemfile' ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler --no-document
        BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install
    - name: Run tests
      run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rake test:unit
